### ISSUE TITLE
Crash - Null  Pointer Exception:

### ISSUE THREAD

**Issue by Yourname942** [Phrille/Vanilla-Boom#6]
Minecraft 1.16.4
Forge 35.1.37
Vanilla-Boom - 1.7.0.1
Crash log: 
https://gist.github.com/Yourname942/0f6632b423808300eac971ee9b5c6241
Latest log: 
https://gist.github.com/Yourname942/1f0bc2055caf4fb03d3f822e33bb02f8

A player fought a netherfish and it crashes.

**Comment by Phrille** [comment]
Please include steps to reproduce. From which mod is a nether fish?

**Comment by recklessrider** [comment]
Can confirm this crash. Seems to be causing a ticking entity crash on our 1.16.4 server when killing silverfish. Suspect it's caused by the iron nuggets being added to the loot table since the crash mentions "at phrille.vanillaboom.loot.LootTableHandler$LootTableDropModifier.doApply(LootTableHandler.java:64) ~[vanillaboom:1.7.0.1] {re:classloading}". 

Crash log: https://filebin.net/tlu5m2q1clgri3ft/crash-2021-02-06_16.55.25-server.txt?t=qwqpocg6 (currently running previous vanillaboom version, but confirmed it happens on latest.)

For me it happens when a silverfish dies. For the above user look like it happens in netherfish, which is probably caused by the same issue.

Just having a netherfish spawn and die causes this. Looks like both the above user and I are running alex's mobs, so both mods may be trying to add to the loot pool. Maybe a way to turn off the loot additions from Vanilla Boom?

**Comment by Phrille** [comment]
This seems to be caused by a bug in Alex's Mobs and not Vanilla Boom. Its loot level event crashes the game and this happens with other mods as well (scaling health for instance). Link: https://github.com/Alex-the-666/AlexsMobs/issues/162, https://github.com/Alex-the-666/AlexsMobs/issues/156, https://github.com/Alex-the-666/AlexsMobs/issues/166, https://github.com/Alex-the-666/AlexsMobs/issues/155. These are just a few. This seems to happen when ever a mod adds a Global Loot Modifier which is used for altering vanilla drops. Alex's Mobs crashes when this happen and as far as I can tell there is nothing I can do about this. However, I may be wrong so please comment again if something seems to be wrong on my part. Thanks.

**Comment by Phrille** [comment]
With the new release of Alex's Mobs I'm considering this closed.

**Comment by recklessrider** [comment]
It's not closed though
They incorrectly closed their issues. There's no new version of alex's

**Comment by recklessrider** [comment]
Wait I'm seeing it now, it's just listed as 1.16.5 unfortunately
